# Site settings
title: "非洲同胞们在哪里"
description: "So I was feeling nostalgic."
baseurl: ""
url: "http://africanbrother.tk"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "abt"
    url: /about
  - title: "twt"
    url: http://twitter.com/shiqinwen
  - title: "git"
    url: http://github.com/qinwenshi
  - title: "rss"
    url: /feed.xml
