# Site settings
title: "非洲同胞们在哪里"
description: "So I was feeling nostalgic."
baseurl: ""
url: "http://africanbrother.tk"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "关于"
    url: /about
  - title: "推特"
    url: http://twitter.com/shiqinwen
  - title: "git"
    url: http://github.com/qinwenshi
  - title: "更新订阅"
    url: /feed.xml
